import { describe, expect, it } from 'vitest';
import { getAutoFillBatch } from '../../src/domain/autofill.js';

describe('preenchimento automático paginado', () => {
  it('processa no máximo uma página e continua do cursor', () => {
    const settings = {
      autoFillWorkedDays: true,
      autoFillStartedAt: '2026-01-01',
      autoFillLastDate: null
    };
    const first = getAutoFillBatch({
      settings,
      workedDays: {},
      todayISO: '2026-01-10',
      pageSize: 3
    });

    expect(first).toEqual({
      dates: ['2026-01-01', '2026-01-02', '2026-01-03'],
      cursor: '2026-01-03',
      complete: false
    });

    const second = getAutoFillBatch({
      settings: { ...settings, autoFillLastDate: first.cursor },
      workedDays: { '2026-01-04': { autoGenerated: false } },
      todayISO: '2026-01-06',
      pageSize: 3
    });
    expect(second).toEqual({
      dates: ['2026-01-05', '2026-01-06'],
      cursor: '2026-01-06',
      complete: true
    });
  });
});
